apiVersion: v1
kind: Service
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app: proxmox-exporter
spec:
  ports:
  - port: 9221
    targetPort: 9221
  selector:
    app: proxmox-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxmox-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxmox-exporter
  template:
    metadata:
      labels:
        app: proxmox-exporter
    spec:
      containers:
      - name: proxmox-exporter
        image: prompve/prometheus-pve-exporter:3.7
        ports:
        - containerPort: 9221
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/pve.yml
          subPath: pve.yml
      # This InitContainer builds the config file using your Sealed Secrets
      initContainers:
      - name: config-builder
        image: busybox
        command: ['sh', '-c', 'echo "default:\n  user: $PVE_USER\n  password: $PVE_PASSWORD\n  verify_ssl: false" > /data/pve.yml']
        env:
        - name: PVE_USER
          valueFrom:
            secretKeyRef:
              name: monitoring-creds
              key: proxmox-user
        - name: PVE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: monitoring-creds
              key: proxmox-token
        volumeMounts:
        - name: config-volume
          mountPath: /data
      volumes:
      - name: config-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ipmi-exporter
  namespace: monitoring
  labels:
    app: ipmi-exporter
spec:
  ports:
  - port: 9290
    targetPort: 9290
  selector:
    app: ipmi-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipmi-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipmi-exporter
  template:
    metadata:
      labels:
        app: ipmi-exporter
    spec:
      containers:
      - name: ipmi-exporter
        # Standard community image for IPMI
        image: prometheuscommunity/ipmi-exporter:v1.10.1
        ports:
        - containerPort: 9290
        args: ["--config.file", "/etc/ipmi/ipmi.yml"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/ipmi/
      # Build IPMI config on the fly from secrets
      initContainers:
      - name: config-builder
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "modules:
              default:
                user: \"$IPMI_USER\"
                pass: \"$IPMI_PASS\"
                driver: \"lanplus\"
                privilege: \"admin\"
                timeout: 10000" > /data/ipmi.yml
        env:
        - name: IPMI_USER
          valueFrom:
            secretKeyRef:
              name: monitoring-creds
              key: ipmi-user
        - name: IPMI_PASS
          valueFrom:
            secretKeyRef:
              name: monitoring-creds
              key: ipmi-pass
        volumeMounts:
        - name: config-volume
          mountPath: /data
      volumes:
      - name: config-volume
        emptyDir: {}