apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: arc-systems

  sources:
    # ---------------------------------------------------------
    # SOURCE 1: YOUR WRAPPER CHART (Git)
    # ---------------------------------------------------------
    # Instead of pointing to OCI directly, we point to your Git folder.
    # ArgoCD will read your Chart.yaml, see the dependency,
    # and run 'helm dependency build' for you.
    - repoURL: 'https://github.com/TataHostIT/tatahostit-platform.git'
      targetRevision: HEAD
      path: infra/cicd/arc/controller
      helm:
        valueFiles:
          - values.yaml

    # ---------------------------------------------------------
    # SOURCE 2: THE RUNNERS (Git)
    # ---------------------------------------------------------
    # (Remains the same - pointing to your configs/runners folder)
    - repoURL: 'https://github.com/TataHostIT/tatahostit-platform.git'
      targetRevision: HEAD
      path: infra/cicd/arc/runners # (Or configs/arc/runners if you moved it)