apiVersion: postgresql.cnpg.io/v1
kind: ManagedUser
metadata:
  name: openproject-user
  namespace: postgres
  annotations:
    # 1. Allow this specific secret to be copied
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    # 2. Tell Reflector to create the secret automatically when the namespace appears
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    # 3. Restrict it only to the openproject namespace for security
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "openproject"
spec:
  cluster:
    name: postgres-shared
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: openproject-db
  namespace: postgres
spec:
  name: openproject
  owner: openproject_user
  cluster:
    name: postgres-shared