apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-shared
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Higher wave to ensure Secrets exist
spec:
  instances: 3
  # https://github.com/cloudnative-pg/artifacts/blob/main/image-catalogs/catalog-standard-bookworm.yaml
  # postgres 17
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7-202602020815-standard-bookworm@sha256:06c79ca5a39f51ffde94195fcd813d2436d1bca5a5bb3b9f522ff4e3b6194f7c

  # CNPG Affinity Schema
  affinity:
    enablePodAntiAffinity: true         # Activates anti-affinity
    podAntiAffinityType: required       # Forces one pod per node
    topologyKey: "kubernetes.io/hostname" # Default

  storage:
    size: 20Gi # Reminder: Can expand later, but cannot shrink
    storageClass: sc-nvme

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: app_db
      owner: app_user
      secret:
        name: postgres-credentials
  # Add new users as required here. Best to create it with existing secret.
  managed:
    roles:
      - name: openproject-user
        login: true
        ensure: present
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: openproject-db-creds
      - name: harbor-user
        login: true
        ensure: present
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: harbor-db-creds
      - name: litellm-user
        login: true
        ensure: present
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: litellm-db-creds

---
# Direct TCP Access for Developers (Layer 4)
apiVersion: v1
kind: Service
metadata:
  name: postgres-external-lb
  namespace: postgres
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.20.20.201"
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    cnpg.io/cluster: postgres-shared
    cnpg.io/instanceRole: primary