apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    # IMPORTANT: Helm repo chart versions are typically without the "v" prefix.
    # If Argo complains, change this to "v1.19.2".
    targetRevision: 1.19.2
    helm:
      releaseName: cert-manager
      parameters:
        - name: crds.enabled
          value: "true"
      values: |
        extraArgs:
          - --dns01-recursive-nameservers-only
          - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true