---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBfYpVEn21FymM5T/mv0DHnSS8iyHeqNz5pFtzfoa6NNZ3aA1KYfSeKEbvdDzHpY02f7Laoh/v+Gv99VsaQb5T9qt4s+qYWPOb+2XSlLsLHaXwrG73d5OI7Xl2egu+iFCVGTuNyEzSHrmC7speZ5jt+nmlqfhnWiRDs9YzgVdLKWOCm1dSGOuFCzwecie4/4lhaGRFOrnLLHoGmUVvrzk2ZS9gPdeMEmFaIlLhELJYM6bHpxo0UmnG/qbnwLT8lRAmaACjxjsuxI7Pa399gNGm6RDlQq5Ym+bKG77Cw7mku75r5SmKEHC1UBbhIhEcKtPlSNR9G31h8RdA2jkxC9tM9WGSHYV3+nz3XLlVl54IGDihMQFhy5TcYU3yl5fBciYRL3ARb9vqhBokSMAK+Jl7pAaZvAKDnarj+f4IgU4n3uXsjLtzZfnEzt8HIERmZeV7NfneYVJp9nVxGBr9XCdOOaKnmRYwU5LtmoSfg/Uj0YN850D0bdp7ouFFUFX0kfuqZvzXSaZlDq0EOutWieNwI0duQd9Mt2SuXrtsmqsNRnni7O73K4lexZfwhWzmKapyPmWmXRqeG9dWQjTRVSFwA2zdBhp//zROU8RFKgIWreErg9ZTitqm1R/1rz0+6w0nnIp9JvwgX+zZaYiM2rwRmNidgRTCOho6c8xraTem6Z9oh3j8tttv9pPqLB4ohKhlzBSjmvDsen13wpbO9/ksgakuF/jCArE10oDqxgsjCv9jQzzMWoiY/
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
