---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csi-rbd-secret
  namespace: storage-system
spec:
  encryptedData:
    userID: AgB8+SF2yY2rLLKYeGVMGX1twI5JyhpfO04Is1pQ+hkXPcbF7d9wSFlNd7bkDxnsU0ho2kScz8H1ua9Ez3xwDAn1OxXb1Oauz2dZNeIW5zjlG/qKuVrGRESCW4oxJH53WXthh2rKH+rf1bRQKCEt5rhg2GtWd0gSROQTXLz1x90GcqYcT5deFkTo1k+YyB2nyR9oqsf+KgEbhb7kxJcD83vHXL5b8YAOZbv9YZDwy7L7bQYQqwbuUEYPH5oh8FcPalA72E7ppxZ8E1s/LtvcEWB6pM04HwzRc10K5zik4Jo0Lcxxb5TPqoyN13npAcjm67fuVAzyud7sVa90c1i6RPjNEC7vfRttvs4fqQ2olLUuTFUtXSz0VGfKXcZINantesWAcCwKj08H1Ksq0QOYyXZa0fiJFbsJuLfJMjtX0KQiam9+jdB4zPDeefCL62XST14DKOswZHOiqvUgg1T5aKfY4xQX6Jeqw1NyPZsPjmOEK7dHOGLbySgDCxvOFHN8iLYjHPzmbMdWk4XTjsoXh+b5/Epv3uYZ5zaNoWmRKmuBA6d6/GUBluwnNYnvL3aU+h+I9NDWqQuyRWDOFrES8tldIQkMdwyf0lmNzeih338vOtRTZkLgu6LTIkyFVipkSb3fuaejseBCyFFWK7pJw9iOWJWAZfPmjHcYuwSgNldqYyj1X39oywojGR3dG8k5+/zK7eo=
    userKey: AgA3lIvvryYGDvBL1UCa2cARioR/awTUNb2AlfFbBtn2hHYmAgj8nqKZAe4ZxofjPITIrk3krK94yPMdvPS3cAAcodKshHx7WHazXNuyMDd2JQWOXGTjRDRvwEgYYos2W6dCnCaH9tddTsBOxlOzJcRqVdpM6VO+BnQsv6PRhjP9SjvgNtBjz2Wg5wtsPormVnQDRXHXD5HfBeNp/LpBxTBCH3o/gBnsp9ndqXMZTbq3oQb8F3NGCgks35lWlyKSJZ726+nMQCQuUY1XTyxobg2V8eUA+h+WwT9aZk2AH0IO9K4rQWzTd2JdB3XBHJLl6q15rfRYEymaPGQVkromF+OgAmxRkUnrflQ4TN/jGBdW1+ynXQQEXI5leVmfqgny6uRjoCZaMeuB2VM2lpQd6zTfC9BHwdJkb4IKmbSJupLAe7BB8r5QWzFUjXQjWinXjyFODhIwn82eC9VJw7IToGDTWCdt9D54xxp5wmTdv5HgGcpdm5UL3ciyvlWCQVC11c7SSVRwmBNNOG7gCt8/GH21cc9c1MZMM15nqDPT+b6nASZQ5ZDpDl8W2lYkahfCytMFYf+1lJdxnCTnkF3OKbdD7kFn9PcHsqvlmuPjCS38k3vYvd16piXtcFgkTVK/k39E1O61diZmIf42t1AA6FLWJYbbSUMYc9ma8TM02A5+OAzxDBl9ZN8eq6yWHtpQfH2iW6aQAH8VdwXMuQKBjp9yQou64IAAYYm0T/R294TTF/bOX8SSYS4m
  template:
    metadata:
      name: csi-rbd-secret
      namespace: storage-system
    type: Opaque
