---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgCyfMuNArQLy2h21Kuw2p8wxSXuwzikkadffzOgBr4kqkYEXyl/oSi081fuCkabMbmaFJjVp7qXL2l6QUwQoOxXghTZXXzYti794KTWNO8vbqjza5zuDRRh3CD+kNLoQK2TdFUiEkpdiQ0iG/f3LpBli7jtVsjjlnvMtTe7HCc9OmLUfPMU+C44biQH1vlgBy6RgZ6q/V75JFjirXSs2vw4Z+D49NhgVB8+hjw61vYgKKhSdQIJHlEn882whHoBUg42JeVWyBC7GA5HzXe/g60s1Yy4JzS4LvjbyyBSwJwNVdvFeF/QkM+Eni7LwyVo8wfY7fYHkOENGz4PlgM6oESaDqSi1skSK34BGByqPRlFLCt5tmEWy8twKDh+VtgtZYG/1sNiXUKcc9p+5xswmt3EaCh5atKXmTp9iun6qKVCsfImp1cOrW9v1j2ujzC+1FTr0bqN9OzoDTbkSbUhT4gCbamkv5Wl8s4VzjNN57IHSFlVKFGxKypaDJjdx+uqKvVruWfRRPPW2MHtUx0vGcD84/EHoWgCrZ9FGhxlrw+vN+67rcChqhH1dONfQlKuD/WKzIQcqmrKPB5ns2p7dQ+hjXt4SJwxNIisFojTRYd0kGBoKWstxdrMlcnAKKNmDXAz2cO8kD2w877ZWoHHVavhqEEhdvwaik7N+FXV61xYKzMW+jGwGMp7ykqfylqGAljzLjOkpoZmQp269Kh8IJ56Vg==
    clientSecret: AgBRJlpDKphby7kRgYNsHqoa+8z1T2d8qUbSXd95NUsct5B3ONawULQNtTrdj3RF0Yzgt+hC5wse0PrfCldcfxNcTbkNlMf7+yp6LHigF8xsr3eO5AiFfrGoIdS3O9T8XLvd6PwDiBQgf5yyyGUbijFfC/5PJ04IIj7oD1ebV1zrhkxoR+w2mAILK8qunAznte+1T3OLBr9GxoAo5Q6Wt/Fc+7oq9GdtJBK0JKgrkIiVuk6z8c5P955qnVjuKy8xLtwqxSJwy65zGnY8PU7A8MzzMrpfAKD6KjnURBSsL+1qPcirS2rAjGhyN9TfnqkF7tY/YkLIE4CvYbU4+78DtKrixnTWWXRWNf/blcWcqa4UBVn83Ij69hE9lmLaOZF3qMZujDsAtPO7HtcL7BEZ6GrCMUVGYgaZVEc2jabBPTeW/dtoLv9X4r05rvxFRLM4hFFl0mdj2OIYbzcYhfRzYW1zPzkK1r57e7yUrDeRrCuDWIdWdRXmSQMpIPCZrnOfLhVaLd2JBj3NtEV2J41vzr0ZUEePkPB9ep1+fE9kdTblV0jhwMSxe6rfFLo+mv9Uk38KOL0+6JeJobMAFbkQC7Wl9dxZuIpq1nerH067Zm1miR4pqRSRsLkCZVRgH/ZrboHHAB931976veUCe/YV+qW+RlfxWVL5abmF6SxsccjY5CqUSMtXsam60Gmw84RL5+CYwkCnipE0Fc+9YZOoX83LrK3L5HpMJ1Dk9FMtN11/uOBH7mov6SZrDElghRxPAitccj5xW4H1wJcW8MD/N7E=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
