---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCu9dqeHT2hVRGepacRF5Q/9RU+st/JBdslCIgaBJEQFqw73M5wzDRmjdv7d3rgZmnfnxGSgMp9n9LSoXvfDsRQJ7VYA/lqHUEPiJeSC0TwRvqGDDBfOqLBYqjmzT76e48kyJNHAtsbzUJ833FlR5ouBsxI4TYpnIx9zTx/0LJ72OiKKiiWi0UTKERPgmCzQmUDoaAP5qvocP6sMqUgO9H6M7lePlP28qAUDEoPXxtiRfNmYovwIgjQO4KZDbZX9cYZa86r+psow6ot09c2t0D+5AdWzxw3K8sGEeI/7+V6IIKUCH3W0sgEBD8T3Lp1FIxNvHc02OHyjZtLs6vWScHmswasrKLxYz+eb+tq0+ngiOymdZ3Ml2nhARAcT7hbYHlOQ4kPNpZ/+Fo/UKnROkZfKgEPD9UvwYbq+DuvUv+9jAbwowRt+vLgku43VuCjJySaPx3rS3lEw7VtcSYFmLeuWWLFKLzgYOUxghLevSXWF0tH1CkGcOAxSvSJJpH3Zr1mcoUrSykjDP24gqPD3gWjDS0w7IR/Ljx4aVST6awJNFFM4dFYvl+o7I/l069sZK6kJxSOqVYLAMzL/nvo+ENVogJLdFrrym5qr78l86LsLdJC1fMUhu1GYSCcS/qRzL/He+0cos/Va68lP20L2zgvsge8reB3lbCyxKfRq+f3Ij/f8RLTbhvhpENgS0TQL8vl43obOcGte5e3jf/Vdy8G5w==
    client_secret: AgAVcsZNMyjVJutGfe0xjPv+kMzF1AAVTASI32tnwvwNKde8+c6H2a8kne7I5GM3lGt2q08SGHyPb7n53TsP9LK6FvD9nNw04MqAFy08+2PjTPDC0T5hIfgbov+Evaoch7Kx2zh7s+ewL8ovtmImBcS+UkpFgsgeCXk8ccV/4wGiqd1LJBPcQdrg42v/7MyIbxCJpO58iGWnzCFVXhHkxuBU4BERHsZWs3vXPyMNPkIAJECyM7OuUk+LlXbtZpLRB353pTGFz2gMV6FA7Miuo4nSGqXs0qUmMA7ncRRLcV9VCQucdu/gKCwzZ622WnhgmNHFKI5iaaXJw/lwDF9KVxJM1oYto+Q+xaNquLqA+8gHP7eULy0YAL9pGWop4KkfmEjysOcK0vlS+qyIIGTykOtUxVQMgrM2iNwIeaquWUmXZb3uQh1L7CVfXwKlee6+LASM0ZEQqf9jFZg0VYXXLGmhx1Is+kP7sRtqU2oOWagXMO1e7XxdsbBQbwjElE9Z8g2u16sRVxkliHxxSCGvp8lppO2Tc+32s6Sqaejr+nmiOkbwhA3ksfLM94nbjl87UwdvCvSwTvgCZ+wrVxiKlx27c7Rtyq+68L9XJGRSw3N5kK2L4CBFMaGX/wSiye3ytQ1LTO8qm2hxRtqqIiMLHghfhdGZDhFQzvODLY8QA8a4eObk6VH4Bu/Lx8a0PCstnQSM9DxQJKO52thquHJRzKNAJOIXTa6Sj8MyoR1Vjwl5cMkkSf6px3ItLVx+IJ8RVP+q3sWP1Fg757y2xj6kkH0=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
