apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-auth-proxy-impersonator
  labels:
    app.kubernetes.io/name: tailscale-operator
rules:
- apiGroups: [""]
  resources: ["users", "groups", "serviceaccounts"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-auth-proxy-impersonator-bind
  labels:
    app.kubernetes.io/name: tailscale-operator
subjects:
- kind: ServiceAccount
  name: operator # This must match the ServiceAccount name in your deployment
  namespace: tailscale
roleRef:
  kind: ClusterRole
  name: tailscale-auth-proxy-impersonator
  apiGroup: rbac.authorization.k8s.io