apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd # Application lives in argocd namespace
spec:
  project: default

  # MULTIPLE SOURCES CONFIGURATION
  sources:
    # Source 1: The Official Helm Chart
    - repoURL: 'https://helm.goharbor.io'
      chart: harbor
      targetRevision: 1.18.1 # Pin your version!
      helm:
        valueFiles:
          - $values/infra/cicd/harbor/values.yaml # Refers to Source 2 below

    # Source 2: Your Git Repo (for the values file)
    - repoURL: 'https://github.com/TataHostIT/tatahostit-platform.git'
      targetRevision: HEAD
      ref: values # This creates the variable $values used above

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cicd # Deploy Harbor into this namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true