apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: jarni-runners
  namespace: cicd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/version: "0.13.0"  # Must match Controller version exactly
spec:
  githubConfigUrl: "https://github.com/talkforceai965"
  githubConfigSecret: jarni-gh-secret
  minRunners: 1
  maxRunners: 10
  template:
    spec:
      hostAliases:
        - ip: "10.20.20.200"
          hostnames:
            - "harbor.tatahostit.com"
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: ACTIONS_RUNNER_LABELS
              value: "jarni-runners"
            - name: DOCKER_CONFIG
              value: /home/runner/.docker
          volumeMounts:
            - name: docker-config
              mountPath: /home/runner/.docker
              readOnly: true
            - name: work
              mountPath: /work
        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: work
              mountPath: /work
            - name: docker-config
              mountPath: /root/.docker
              readOnly: true
      volumes:
        - name: work
          emptyDir: {}
        - name: docker-config
          secret:
            secretName: arc-docker-config
            items:
              - key: config.json
                path: config.json