apiVersion: v1
kind: Namespace
metadata:
  name: storage           # For Ceph/CSI
  labels:
    # This disables the safety lock for this specific namespace
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: networking          # NGINX and MetalLB
#  labels:
#    pod-security.kubernetes.io/enforce: privileged
#    pod-security.kubernetes.io/audit: privileged
#    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    # Node Exporter requires hostPath, hostNetwork, and hostPID access
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems         # For GitHub Runners
---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd          # For GitHub Runners
  # ALLOW PRIVILEGED PODS (Critical for Dind)
  pod-security.kubernetes.io/enforce: privileged
  pod-security.kubernetes.io/audit: privileged
  pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-tunnel
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-apps
---