apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # SOURCE 1: The Upstream Helm Chart
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: loki
      targetRevision: 6.49.0
      helm:
        valueFiles:
          # This references the file in Source 2 using the $values variable
          - $values/infra/logging/loki-values.yaml

    # SOURCE 2: Your Git Repo (contains the values file)
    - repoURL: 'https://github.com/TataHostIT/tatahostit-platform.git'
      targetRevision: HEAD
      ref: values
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    # SOURCE 1: The Upstream Helm Chart
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: promtail
      targetRevision: 6.17.1
      helm:
        valueFiles:
          - $values/infra/logging/promtail-values.yaml

    # SOURCE 2: Your Git Repo
    - repoURL: 'https://github.com/TataHostIT/tatahostit-platform.git'
      targetRevision: HEAD
      ref: values