apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: test-apps
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo
        ports:
        - containerPort: 9898
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: podinfo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-pvc
  namespace: test-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-nvme
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: test-apps
spec:
  ports:
  - port: 9898
    targetPort: 9898
  selector:
    app: podinfo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  namespace: test-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - podinfo.tatahostit.com
    secretName: podinfo-tls
  rules:
  - host: podinfo.tatahostit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: podinfo
            port:
              number: 9898