---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgAQnE2ZwhSJ8D+UgFuEGUQKenVO3/SA0fQiMuMaJZzTx4HdreLckKcN08UZbAScf6DtkrjqA1zkI2JgRs9wiBYKb462IKG2aIxOhl8x24s2x96izhvWqfnTwF1OEvNLhyamVgLg9+QYhMbJpTErpcQsM7rY5Va06cPTR0pfwo03d0Yv8zuDSW9E8OCQu7fml45+VfiDqdt2tq216lNQ8PV9q1QkOhEJDlQjutyr4D9h2cHNyBj+RHjHAKLy9ro+aZjvjLoDveLm2SnQ5ftj3YmnAJw/sOWcQDEifGNudmWYLHmkQkD7JUfSYGrvTVYJ5tB2U6ADUiP3cQZbvNdg5IUl0x1jc0TcfRn8CvC4+l0+yOaAszbVNMPSBUEnIhBpCm6OKhXg8HKr4nx6avy/wSvr3leAaI9safObwwpD/AnGdLEYnSil3h/dWVG++T45Y0QGG141CEFm7wFWBRIqtJFIBt2ilFDQl9RbVbN2mzOeYizZZl0zVl/MllDsHI8kXOBB/l55jkAsRpw8V4hJ/eycFVgUUwm30m4LO5o3qB8Z003S4Si+Ztw2eTXO5KJsbhCAac/CKeJh68C9sEHEDgaPkbTfh8UrjL/wXE4LfUbqUQq6sbWXqRrmZFsUzZdbLEvuU6WJgbuS6L7p6BR6kXMI+cY+lHIxVfz9/GeN1PoV9vKmmGSxI1dEMfukopw/fJSVxy8Tj8xhpV+UZ6zLWvhzBA==
    clientSecret: AgA7hJOmRtCunr+VOMJOVm/g90jcUgPQZwBfq1rOhNkIYXBaNtu5DVGPYxG6bUckpEGQm5L7imNvZ4KjPfbPOmcKZIdh8UO/EP8cPvGLiIc+w58qOb4bxaB92IUW/Z0Wcjy5oZfWi3OJsTSrLiVEJ5EHsQPSoXxj8Rofxqe3YfDrar2uQDQRaYCUEvWTQOGC0AQAn4RebzFdiYhRdPVQi5YclepmOhVgbTXvqPM8VbtzefBb/l3BZfD6+Dy+lfaOdQ2M/ljQaYrMo3fAhwsDJ4fN/LG1ZhRPVT6mr5heft+ud95DyGvW/GbdjZMmUVzbM5YYTKc3B1iTMEpQrjBZOhPvbF7PS3cjRBFSXUPw6knoOHd8Y1feJVVjIsZIBjUj9/DzzRrSkwpRH0FYh6PZ9OxJmEj8fL4MR843D0jHgtiB5GVuMSAzAG5UOavnbtOANHczxsxj9g/7/G8ltlfWboOko3AHbIxx1mXoCZPTtuIx/Y8qcFFavrVpjjAf3vfyGffAbN0vpTzJ3V/BxUSIfrSMIAH0L//WH1F2tDDwKEKhvaj3d1BOXjfVSjipO9iqAd0YC+OM04QYwOztk9Yl3QgV1hvKhc1TY7+GEPdZrVBIqiEbXhiJ5ZKvsh8B/hXtvcLtHI8e0Yg9TNrYldVV2a7B9ja0QTfpNjYTaefPfqgNFR8ZQaCbESq4gOPAth9nXNv3PuPPV4eeL/NWFqJX7SLxsKORoBNUKNlOGlmzr9GuLEKEv0h2tEEq73DEfQIU0sDGgPvGrhCAazpVzKBRtcA=
  template:
    metadata:
      name: tailscale-oauth
      namespace: tailscale
