apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: mongodb-cluster
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
    infra-component: databases
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  crVersion: "1.21.2"
  image: "percona/percona-server-mongodb:7.0.28-15"
  imagePullPolicy: IfNotPresent
  updateStrategy: SmartUpdate

  # Secrets reference
  secrets:
    users: mongodb-cluster-secrets
    encryptionKey: mongodb-cluster-encryption-key

  # Replica set configuration
  replsets:
    - name: rs0
      size: 3

      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"

      podDisruptionBudget:
        maxUnavailable: 1

      resources:
        limits:
          cpu: "2000m"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "2Gi"

      volumeSpec:
        persistentVolumeClaim:
          storageClassName: sc-nvme
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

      # Expose with MetalLB
      expose:
        enabled: true
        exposeType: LoadBalancer
        serviceAnnotations:
          metallb.universe.tf/address-pool: production-pool

      configuration: |
        operationProfiling:
          mode: slowOp
          slowOpThresholdMs: 100
        storage:
          wiredTiger:
            engineConfig:
              cacheSizeRatio: 0.5
              directoryForIndexes: true
            collectionConfig:
              blockCompressor: snappy
            indexConfig:
              prefixCompression: true

  # Sharding configuration
  sharding:
    enabled: false

  # Backup configuration
  backup:
    enabled: false
#    image: percona/percona-backup-mongodb:2.12.0
#    serviceAccountName: percona-server-mongodb-operator
#
#    storages:
#      ceph-local:
#        type: filesystem
#        # FIX 2: Correct field name is volumeSpec
#        volumeSpec:
#          persistentVolumeClaim:
#            storageClassName: sc-hdd
#            accessModes: ["ReadWriteOnce"]
#            resources:
#              requests:
#                storage: 200Gi
#
#    pitr:
#      enabled: true
#      oplogSpanMin: 10
#
#    tasks:
#      - name: daily-backup
#        enabled: true
#        schedule: "0 2 * * *"
#        keep: 30
#        storageName: ceph-local
#        compressionType: gzip

  # Monitoring
  pmm:
    enabled: true
    image: percona/pmm-client:3.5.0
    serverHost: prometheus-operated.monitoring.svc.cluster.local
    resources:
      limits:
        cpu: "300m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"