---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-admin-auth
  namespace: rabbitmq-system
spec:
  encryptedData:
    password: AgBtTR4sNPHglj3GqkjvTYZT3tIlP4TBNIOneLrf58qEh+FqmwYZ3awGqWQZC2mWbc+4o+ZBiiE3sXRhDtWgR+2vfGkQCvTM04MgADt1/Om7MLYU6r3AUsH9FvFeRwoDNeWJbxOK6t4RMOxDUlgudEOzq0SPj0AbI5HY9ot9XohTOEXMDyD+FXNGaZjtg8KNCJnruOV8xaeyBngSMi5nqVxg0F1gNM2zdmeuJHJpEE/H1BZXSM5wSwLBOyuc6lRnmIIbr+ClY+Qi5+e7CXl8w/AnHAIyFbkpyfUSSR053Um+L39PoGVSIlLTcHj7w7+94GfnKs4N8zRrx5T53UvtIisU4bosOQd/X3K5KJX/9Prr3Q96KUn5RyfujnZ27vW7sUEhBMIXpFs9F5t7dXzT8X4gdPIDKxubEPq7NZHl9cmBvImch5HGFM7C8HHIQgjIEowncgpP/MFUxhkKHwZqugNWS1Ays4i9cmKUhw5jizA2tbOaH1t0pEtRi2dgvBSfYE4UdBX2gTY2tjKKB5jK+FuA9MAnpkBybZ7gNAc29M8926/nMj7/zwn7cRhBhrP2JR3emh381ng8kFM0emU7WJwsrJMeb9nkaSrwDNMf77ptENwVnq0YnutGuN5+LmWfmbpVOXszbHGzhiW2xANDfLhJMuYncNoAlpfK0bckWIY9V0QNPAxgxpLU2HAA2mYrHwL9JlayzoEgwgG5iejK9N3q+ro=
    username: AgA9LD1qG9FHe0W1NYi06+/GKRSLloyBcSsbVbqyL2L2CliKsgTiyO4ON0JktzFrHuzxbECZqLCw5YkbG2OP0GiIoDqJgyhsc/EeX26WdL8tTgfKjzX7yFD4XnLx8wl47w0N4gOU6tUo7KJDaMqWl/l1kZTtv5jQczSH7tgCfys8ebsGIEOtzLllWwnqjp/829adjB/9Gc89+Ad0OADk37e3F7ckcupfTDSbZMoyoqDXTuFfrNvWNLpIZEwxODUZDlC31N/xEqxUPApk6g3UsfdHdbhzI2OisXsdONlePQuhP/D5wHoqEZ0gqkoKfv0yLckpTrxBqotRsjVUxXMCoT1qsali5rnseTcKyJn1C21CVpLNpao5bal7pTxCK2skq4KH+OsYuXD7qlynAEmOBPnAEnYpEDyyQq9Uvz3EeqQsHrWCv/bj4py+Pi3u9c4qIel8nlzNtA4vYCIdr3qeq76XW4gF2AkhCnZoRrsaMQSkCZ0lhawcrMPGXBBarjConxgPZx7U1hlxw1QIS55K1pyMaUZ3LTG3W+LKPRF7mUB6UJCKOWLAP9wTFSyWnwMALsFB7kElB+/nHyny+XIZ0sN1kQziIzIuUsiEYLl4yl7nv97Z0O7FJ6WKAA6uZvJywLjZFXZlwju2E95amyqa7aBXWJVCU+BW8m4EsP8XzSN/i5FnznFlFzEN+6p7v53i5JzazwPixw==
  template:
    metadata:
      name: rabbitmq-admin-auth
      namespace: rabbitmq-system
