apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare-tunnel
  labels:
    # Ensure this matches your Prometheus Operator's serviceMonitorSelector
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: cloudflared
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - cloudflare-tunnel