---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAuaqzjtDKUCf3vdjg3BBqO2xo77FkhNtuWMGAP0gD9FRQAAtVqSzuMEyLpq+w+WtcHtMLG/dFTWBuTVdqSMf7TkkQ84fJcHSk+mt56qn1YXJBfJrzhWS0fb0PoS5qSY1cO6Qqcns/g39e8kDocKPpUQIQ4n18rIjdHwlxdapzzs4SxrBOLxpTClcHae/rPyfmIoxxL07xMYQ+JRDr8RKJaKlXL+cWEtP1pBb2PS/SJw3hh6D7n1yrF7xDauP6MJWWERvmUnkfYuXgDWsqvTBohQ8RSy5vQtU4dq/Qa/DaO4zkJ5jFW9c8LAZXLswO+Ygp3+oOZ5Ovvni9cN7pp1wIZm1J/w9D3ZrXCMEl9KlH9pWkLl8O0DDNABve021XC2PF9qTowcfNrWqWUHBRuHZg/NqsM86dvZ4Ze587i0Dkv+a1JbXccIZkDcrvJ2EcHoO2Hu9hzB86SXAkiVvZAPruA5C9MSp+EVgcFIBXVIX5ATUdwQEjvekpGqvtp1vcyhMGEFsra/5rt9EE3tJ5b1r7sg9cCNskCfVqk5pbPUNZrfvc5f9rbdo6m+qcCB1GZXdihXbcFyzX6EwsjLvSnUnTmNdw+n40p4kqxuVnkyRi82zckEBE66oK6u+CRV2TyFFY1I29TqY6ffTH0PKWjHgdCFRfb44RwnfZcAUDNBxjLneRCrQawKux32RQ696GEFfgoj33hZW1lISjkrey/PRU6Bti3Mgc9/sXIaL5lmQgi9AgPAlTn8FG4/ZKeLdVe8ToIvd6mU4J/XhDyItMqTJfMqgXIfpgmK5pw/u4UOPVMnSvvgG6eiI4lp1nPqvP3x7je5KrOVCUYI8IcnFtTidUevMf82JG8vIWhW6maQ7LH8Tdp/vt+F88DxUMMjiSSE/e/K+7QNGCP2ozaumSIptBwRpko96tm1BB2/V0/jIVSOfyjjufblcti
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflare-tunnel
