---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    credentials.json: AgBUlsuTc9w25M5EIz76IJ0G77CTCi9QwP/IlNAv2pgf1qr1TgPY3UkdR0UOOeqis4D6IXRFNmajfQQeV54CGKzQk+Nr7rWgGN/MQVgh4yJQ2W90M/fpBYLZJwmLeQzqn3TlBaNo4MOXfbYawsA+iQa7ftJBO83hobO2NVufqc0hLzfJCiAvyjHtBSb76uCxScB8c0H/YtfE3IOrlPPB8w96wtNYzHLeBeG4Qk4OGpvAss45h30/ndX2d8enTohSuAiPVOxwvf22JJP/C4TjczK/9Cxezmm5QWCpTqX23f48fasxDXF8/m6cLKBHdUutsRQp5lzZZs/AdV5uqRScQeuZwkoqtu5v1yabRQIZLoQWMVereMT8KBtYB+TIDoGkKezjA0od2dniALREYvFceZqHvgPld0nsUxI17aLMwm3uI7+vAsolv2wukyOfBQA70IATV/GVoUyoAXhUEV0+ivQ+sK+XpWalkiKA1IwEZjJgHN2lvCi0ql7evD1j2YjrFE2Ml8vtc0Ga0N3UUc6Nogt+FW3KjeeggcAqp7QfTXUJS0Tjv00DOwrWxoI15U7W7x/hescBHiamB6sDPCEV0Zr/JCMGb6V8aW9jlDWX0SuCt0ywSJZ9mNy4n0PI1s6lGPC1ltldxmvdUjJPpgCANQJX5IJhHTT8CiMsryiJeoaRrqUGirhpxSRVkQyZnTMoxQKmX6cg2cqs9l+SEyRflEzalslhJYWuDFCY3AdUeWkpdccB4LCODiDbexEIflfJBiQOm1jkH1UlDOTmC4sdunFPm3BF6lSpKAHJHG+2+xgeJUFoi1TAo2g26RWtxeAJbEaXcQ0Z4/e7geeLE4wVwK6S7+pLhPIHUzz3FWR+wRH9ypaz3ZvDjS/6QLsE2sh621Fei6Jx1e60nGF/kFRDMBowmzdAuo66W3kgaJDihuKZC7JA
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflare-tunnel
