---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBJ9j42tKtVxWLifPGx+g+BbVnNVeGJpQsU/2ZWUtBed/x7vvRppMy97H558qVef6D69Y2MvNwEl1h0DCaZmdkLB6KgEQov4IFQomw7g5auXMaMtviiMTfP2/VeLAaRgTZGVcUfIGjmTTS9wVvagfJbfCrKxVclaorqPDJWKU4MIu3B279kP6TIkF721KNahNkwbPRkx9RpMGqsWnzHzeCMF4XEA2vXBEvCka7xWsTi5S00a9aUNWD1hvBVBG+oCAT0VRPILGLq65KLRc2Z8VmnlWWqudzIEhjJ34bJ/88y1beFsOMlZSxyW0Duu8jwKz1q2ilWXUauolNoNjV5uXyMHxo16TWyqBRBrT8cgmVgqTcqY+zyQrUEM2PsvuAOUB77ILXS5vxjWeUapnrANacCY/exhq6QdWKJf4TnCmXYw2U12RjxBqNXRDuQxJTy6jFgDQaYl+1NmGIE/ih7QH4KOVVEi0j5sqeNeSMrHRkHMlumlzX6rkXUFiOOXit6SYFfwoYBL3uMvqc5JI0zIxYGD0tq8ySNs/D2RRo8vmmm1KSAUG9q1c9Uxj4yHFaFqA1o/DHcpp/Umcn/aPl6oplnjmqyKNtJrSdYxgAFDDJiS7EfB709S+TcDAxPdOtXMRNQJSEKTShONqEiGVnmHDqCt/HIkhb5xape4GsV4NRl4/ai3O+Ex3UJ5dNzlfgGQsikJiHMpmGLDfb9P+wKkjpNMUYw0FwoMQcMo9UeJAQcHOsWB18Q32qvKXEobSZOqKq6EL8Jzmg7uRU7PKoZqYSnwk++Uh/UcTa84072dGgv5VvD1IvzS9r4loWMY/6366CWVtbBNCGAi2ERawSfL+8ZbqNv25UAI/7vRsgrLej/d+fK5FNzoveRa7ngxXJUBCOk/JD+NaOdMjkFgqhY2iwA4lIv1Q9lyJX2FS+bPR3x5w6fNOTYx7UE
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflare-tunnel
